AWSTemplateFormatVersion: 2010-09-09

Resources:
  BorderlessHouseMemeber:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'borderless-common-fee'
      AttributeDefinitions:
        - AttributeName: 'House'
          AttributeType: 'S'
        - AttributeName: 'Timestamp'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'House'
          KeyType: 'HASH'
        - AttributeName: 'Timestamp'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
